### PR TITLE
Create a bare-bones operator

### PR DESCRIPTION
**Pull request by devinsba**
Component to run and provision Zipkin servers given a Kubernetes custom resource definition

Screen Shot 2019-10-24 at 9 24 09 AM

### CODE REVIEW

**Comment by devinsba** [comment]
Thanks, that's a good point. The fabric8 library seems to be the best one for actual development but I can definitely start from YAML and modify within the app, I've seen a few examples of that around

**Comment by adriancole** [comment]
Thanks, mainly it would be nice to ensure we don't hint there's a coupling to fabricate in any way, unless there is. Using fabricate in a demo is fine (ex example-fabricate). Similar exists in our seldom used zipkin-api-example. We focus on the content in zipkin-api, and example usage elsewhere.

The overall main point is just to keep the review easier so people can just look at the source files and not all the java ceremony (again unless that's somehow coupled)

**Comment by devinsba** [comment]
I think maybe there is a disconnect around the purpose here, the code here isn't meant as an example, it's meant more as an appliance application that is installed into a kubernetes cluster. It maintains a zipkin deployment and configuration. My hope is to include discovery of other resources running in the cluster (cassandra, kafka, prometheus, etc.) and wire those into the server as available

**Comment by adriancole** [comment]
I see I think :) ok so this is a control plane thing. I will bow out as I
dont know anything about the options here. Maybe fodder for readme is if
there is literally only fabricate that people use or if this is somehow
language agnostic. being new to this I have no idea.

**Pull request closed without merging**
